services:
    redis:
        image: redis:latest
        ports:
          - "6379:6379"
        volumes:
            - ./redis:/redis

    flask-app:
        image: app-image
        container_name: flask-app
        build: .
        restart: always
        ports:
            - '5001:5000'
        volumes:
            - .:/code

    worker:
        image: app-image:latest
        container_name: worker
        depends_on:
            - redis
        command: rq worker --url redis://redis:6379
        links:
            - redis
